from django.db import models


class Qrytmphpp(models.Model):
    productid = models.IntegerField(blank=True, null=True)
    whsid = models.IntegerField(blank=True, null=True)
    nhpp = models.DecimalField(max_digits=65, decimal_places=12, blank=True, null=True)
    stokakhir = models.DecimalField(max_digits=41, decimal_places=4, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'qrytmphpp'


class RtTxrcv(models.Model):
    rtid = models.AutoField(primary_key=True)
    rcvidf = models.IntegerField()
    biayabm = models.DecimalField(max_digits=10, decimal_places=8)
    biayacukai = models.DecimalField(max_digits=10, decimal_places=8)
    biayappn = models.DecimalField(max_digits=10, decimal_places=8)
    biayappnbm = models.DecimalField(max_digits=10, decimal_places=8)
    biayapph = models.DecimalField(max_digits=10, decimal_places=8)
    biayalain = models.DecimalField(max_digits=10, decimal_places=8)
    total = models.DecimalField(max_digits=10, decimal_places=8)

    class Meta:
        managed = False
        db_table = 'rt_txrcv'
        db_table_comment = 'table tengah antara txrcv dengan segala biayanya, mempengaruhi HPP'


class Tmppindahanstok(models.Model):
    urut = models.CharField(max_length=1)
    keterangan = models.CharField(max_length=25)
    rcvid = models.BinaryField(blank=True, null=True)
    rcvno = models.CharField(max_length=1)
    rcvdate = models.CharField(max_length=10, blank=True, null=True)
    productid = models.IntegerField()
    namabarang = models.CharField(max_length=200)
    qtyin = models.DecimalField(max_digits=41, decimal_places=4, blank=True, null=True)
    qtyout = models.DecimalField(max_digits=45, decimal_places=4, blank=True, null=True)
    status = models.CharField(max_length=1)
    rcvwhs = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'tmppindahanstok'


class Topord(models.Model):
    purchaseid = models.AutoField(primary_key=True)
    purchaseno = models.CharField(max_length=4, blank=True, null=True)
    requestid = models.IntegerField(blank=True, null=True)
    purchasedate = models.DateTimeField(blank=True, null=True)
    paymentterm = models.IntegerField(blank=True, null=True)
    supplierid = models.IntegerField()
    receivedno = models.CharField(max_length=10, blank=True, null=True)
    receiveddate = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'topord'


class Toreqs(models.Model):
    requestid = models.AutoField(primary_key=True)
    requestno = models.CharField(max_length=50)
    requestref = models.CharField(max_length=50)
    requestdate = models.DateTimeField(blank=True, null=True)
    userid = models.CharField(max_length=50)
    categoryid = models.IntegerField()
    requestto = models.CharField(max_length=50, blank=True, null=True)
    totalqty = models.DecimalField(max_digits=10, decimal_places=0)
    totalamount = models.DecimalField(max_digits=10, decimal_places=0)
    statusid = models.IntegerField()
    finalstatus = models.IntegerField()
    requestnote = models.CharField(max_length=50)
    requestpriority = models.IntegerField()
    locationid = models.IntegerField(blank=True, null=True)
    createddate = models.DateTimeField(blank=True, null=True)
    createdby = models.CharField(max_length=50)
    updateddate = models.DateTimeField(blank=True, null=True)
    updatedby = models.CharField(max_length=50)
    approvedesc1 = models.CharField(max_length=50, blank=True, null=True)
    approvedesc2 = models.CharField(max_length=50, blank=True, null=True)
    spvapprovedate = models.DateTimeField(blank=True, null=True)
    approvedate1 = models.DateTimeField(blank=True, null=True)
    approvedate2 = models.DateTimeField(blank=True, null=True)
    reason1 = models.CharField(max_length=200, blank=True, null=True)
    reason2 = models.CharField(max_length=200)

    class Meta:
        managed = False
        db_table = 'toreqs'


class Toreqsdetl(models.Model):
    requestdetailid = models.AutoField(primary_key=True)
    requestid = models.IntegerField()
    itemgroupid = models.IntegerField()
    itemid = models.IntegerField()
    qty = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=0)
    amount = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    supplierid = models.IntegerField(blank=True, null=True)
    brandname = models.CharField(max_length=50, blank=True, null=True)
    unit = models.CharField(max_length=10, blank=True, null=True)
    useddate = models.DateTimeField(blank=True, null=True)
    usedfor = models.CharField(max_length=50, blank=True, null=True)
    itemtype = models.CharField(max_length=50, blank=True, null=True)
    itemnote = models.CharField(max_length=100, blank=True, null=True)
    statusid = models.IntegerField()
    approveddate = models.DateTimeField(blank=True, null=True)
    approvedby = models.CharField(max_length=50)
    createddate = models.DateTimeField(blank=True, null=True)
    createdby = models.CharField(max_length=50)
    updateddate = models.DateTimeField(blank=True, null=True)
    updatedby = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'toreqsdetl'


class Txpo(models.Model):
    poid = models.BigAutoField(primary_key=True)
    pono = models.CharField(max_length=45, blank=True, null=True)
    podate = models.DateField(blank=True, null=True)
    ispolokal = models.SmallIntegerField(blank=True, null=True, db_comment='1;Impor;0;Lokal')
    isprq = models.SmallIntegerField(blank=True, null=True)
    supplierid = models.IntegerField(blank=True, null=True)
    pocurr = models.CharField(max_length=45, blank=True, null=True)
    porate = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    potop = models.IntegerField(blank=True, null=True)
    poket1 = models.CharField(max_length=255, blank=True, null=True)
    poket2 = models.CharField(max_length=255, blank=True, null=True)
    pokontrakno = models.CharField(max_length=45, blank=True, null=True)
    pokontrakdate = models.DateField(blank=True, null=True)
    tipebiaya = models.IntegerField(blank=True, null=True)
    po_gross_val = models.DecimalField(max_digits=19, decimal_places=4)
    subtotalpo = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    discpct = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    discval = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    po_subtotal_after_disc = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    ppnpct = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    ppnval = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    gtotalpo = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    totalkonversipo = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    local_po_subtotal = models.DecimalField(max_digits=19, decimal_places=4)
    local_po_tax = models.DecimalField(max_digits=19, decimal_places=4)
    local_po_total = models.DecimalField(max_digits=19, decimal_places=4)
    totalbayarpo = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    totaldppo = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    totalbiaya = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    totalkarton = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    totalvolume = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    totalberat = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    statuspo = models.IntegerField(blank=True, null=True)
    statuspodel = models.IntegerField()
    bunitid = models.IntegerField(blank=True, null=True)
    printed = models.DateTimeField(blank=True, null=True)
    printedby = models.CharField(max_length=45, blank=True, null=True)
    totalapprove = models.IntegerField()
    approved = models.DateTimeField(blank=True, null=True)
    approvedby = models.CharField(max_length=45, blank=True, null=True)
    viewed = models.DateTimeField(blank=True, null=True)
    viewedby = models.CharField(max_length=45, blank=True, null=True)
    isrejected = models.SmallIntegerField(blank=True, null=True)
    rejected = models.DateTimeField(blank=True, null=True)
    rejectedby = models.CharField(max_length=50, blank=True, null=True)
    rejectedreason = models.CharField(max_length=255, blank=True, null=True)
    requested = models.DateTimeField(blank=True, null=True)
    requestedby = models.CharField(max_length=255)
    iscancel = models.SmallIntegerField(blank=True, null=True)
    cancelled = models.DateTimeField(blank=True, null=True)
    cancelledby = models.CharField(max_length=45, blank=True, null=True)
    isclosed = models.SmallIntegerField(blank=True, null=True)
    closed = models.DateTimeField(blank=True, null=True)
    closedby = models.CharField(max_length=45, blank=True, null=True)
    sendemailnotif = models.IntegerField()
    deliverydate = models.DateField(blank=True, null=True)
    po_fpajaknorcv = models.CharField(max_length=500, blank=True, null=True)
    po_inv_no_supplier = models.CharField(max_length=255, blank=True, null=True)
    po_sj_no_supplier = models.CharField(max_length=255, blank=True, null=True)
    po_fpajaktglrcv = models.DateField(blank=True, null=True)
    treceived_val = models.DecimalField(max_digits=19, decimal_places=4)
    tinvoiced_val = models.DecimalField(max_digits=19, decimal_places=4)
    created = models.DateTimeField(blank=True, null=True)
    createdby = models.CharField(max_length=45, blank=True, null=True)
    modified = models.DateTimeField(blank=True, null=True)
    modifiedby = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'txpo'


class Txpod(models.Model):
    podid = models.AutoField(primary_key=True)
    poidh = models.IntegerField(blank=True, null=True)
    productid = models.IntegerField(blank=True, null=True)
    ketbarang = models.CharField(max_length=255, blank=True, null=True)
    kettambahan = models.CharField(max_length=255, blank=True, null=True)
    unitprodpod = models.IntegerField()
    qtypod = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    qtypodr = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, db_comment='qty yang diterima berdasarkan podid')
    qtypodi = models.DecimalField(max_digits=10, decimal_places=2)
    biayaratepod = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    biaya2 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    biayacurrpod = models.CharField(max_length=45, blank=True, null=True)
    kartonpod = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    volpodm3 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    beratpodkg = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    estpod = models.DateTimeField(blank=True, null=True)
    uomid = models.IntegerField()
    stprod = models.IntegerField()
    pricepod = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    discpctpod = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    discvalpod = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_price_after_disc_1 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_disc_pct_2 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_disc_val_2 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_price_after_disc_2 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_disc_pct_3 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_disc_val_3 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_price_after_disc_3 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_disc_pct_4 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_disc_val_4 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_price_after_disc_4 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_disc_pct_5 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_disc_val_5 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_price_after_disc_5 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_disc_pct_6 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_disc_val_6 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_price_after_disc_6 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_ppn_pct = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pod_ppn_val = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pricepoda = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    created = models.DateTimeField(blank=True, null=True)
    createdby = models.CharField(max_length=45, blank=True, null=True)
    modified = models.DateTimeField(blank=True, null=True)
    modifiedby = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'txpod'
        unique_together = (('poidh', 'productid'),)


class Txrcv(models.Model):
    rcvid = models.AutoField(primary_key=True)
    isretur = models.SmallIntegerField(blank=True, null=True)
    isreturpo = models.SmallIntegerField(blank=True, null=True)
    isstockawal = models.SmallIntegerField(blank=True, null=True)
    istransfer = models.SmallIntegerField(blank=True, null=True)
    isinvoice = models.SmallIntegerField(blank=True, null=True)
    trfrefid = models.IntegerField()
    bdp_refid = models.IntegerField()
    rcvno = models.CharField(max_length=100)
    rcvdate = models.DateField(blank=True, null=True)
    supplierid = models.IntegerField(blank=True, null=True)
    poidh = models.IntegerField()
    currencyid = models.CharField(max_length=10)
    containerid = models.IntegerField(blank=True, null=True)
    rcvwhs = models.IntegerField()
    rcvnote = models.CharField(max_length=510, blank=True, null=True)
    customerid = models.IntegerField(blank=True, null=True)
    rcvcurr = models.CharField(max_length=10, blank=True, null=True)
    bunitid = models.IntegerField()
    rcvwhsto = models.IntegerField()
    totalrcvq = models.DecimalField(max_digits=19, decimal_places=4)
    iscancel = models.SmallIntegerField(blank=True, null=True)
    canceluser = models.IntegerField(blank=True, null=True)
    canceldate = models.DateTimeField(blank=True, null=True)
    isold = models.SmallIntegerField(blank=True, null=True)
    apod = models.IntegerField(blank=True, null=True)
    islunas = models.SmallIntegerField(blank=True, null=True)
    totalbayar = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    kursbeli = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    kurseval = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    kursbl = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    isshpl = models.SmallIntegerField(blank=True, null=True)
    coa32 = models.IntegerField(blank=True, null=True)
    totalretur = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    iskys = models.SmallIntegerField(blank=True, null=True)
    reftrxid = models.CharField(max_length=64, blank=True, null=True, db_comment='invoiceid')
    pcrcv1 = models.BigIntegerField()
    pcrcv2 = models.BigIntegerField()
    statusrcv = models.SmallIntegerField(blank=True, null=True)
    iskontrabon = models.SmallIntegerField(blank=True, null=True)
    iscashrcv = models.SmallIntegerField(blank=True, null=True)
    printedby = models.CharField(max_length=100, blank=True, null=True)
    printed = models.DateTimeField(blank=True, null=True)
    ppnvalrcvh = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    discvalrcvh = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    subtotalrcv = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    totalpotongan = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcv_subtotal_after_disc = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    ppnvalue = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    totalrcvm = models.DecimalField(max_digits=19, decimal_places=4)
    grandtotalrcv = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    tkonversibeli = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    fpajaknorcv = models.CharField(max_length=500, blank=True, null=True)
    fpajaktglrcv = models.DateField(blank=True, null=True)
    inv_no_supplier = models.CharField(max_length=255)
    sj_no_supplier = models.CharField(max_length=255)
    paramst_pch = models.IntegerField()
    tinvoiced_qty_val = models.DecimalField(max_digits=19, decimal_places=4)
    tinvoiced_jml_val = models.DecimalField(max_digits=19, decimal_places=4)
    created = models.DateTimeField(blank=True, null=True)
    createdby = models.CharField(max_length=30, blank=True, null=True)
    modified = models.DateTimeField(blank=True, null=True)
    modifiedby = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'txrcv'
        unique_together = (('rcvno', 'rcvdate', 'rcvwhs', 'customerid', 'rcvcurr', 'supplierid'),)


class Txrcvd(models.Model):
    rcvdid = models.AutoField(primary_key=True)
    poid_d_idf = models.IntegerField()
    rcvid = models.IntegerField()
    rinvoiceid = models.IntegerField(blank=True, null=True)
    rinvoicedid = models.IntegerField(blank=True, null=True)
    rcvidref = models.IntegerField(blank=True, null=True)
    productid = models.IntegerField()
    noteline = models.CharField(max_length=8000, blank=True, null=True)
    ketrcv = models.CharField(max_length=100, blank=True, null=True)
    uom_idf = models.IntegerField()
    qtyrcv = models.DecimalField(max_digits=19, decimal_places=4)
    qtydus = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    qtyunitdus = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    discvalrcv = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    produnit = models.CharField(max_length=100, blank=True, null=True)
    konversircv = models.CharField(max_length=10, blank=True, null=True)
    coa33 = models.IntegerField(blank=True, null=True)
    discvalrcvd = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    skuid = models.CharField(max_length=200, blank=True, null=True)
    kursbelid = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    ongkos = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    ongkosf = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    expireddate = models.DateField(blank=True, null=True)
    hrgawalrcv = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    hargadasar = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_disc_pct_1 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_disc_val_1 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_price_after_disc_1 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_disc_pct_2 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_disc_val_2 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_price_after_disc_2 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_disc_pct_3 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_disc_val_3 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_price_after_disc_3 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_disc_pct_4 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_disc_val_4 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_price_after_disc_4 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_disc_pct_5 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_disc_val_5 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_price_after_disc_5 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_disc_pct_6 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_disc_val_6 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_price_after_disc_6 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_ppn_pct = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    rcvd_ppn_val = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    pricercv = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    hrgmodal = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    invprcprice = models.DecimalField(max_digits=19, decimal_places=4)
    invoiced_qty_val = models.DecimalField(max_digits=10, decimal_places=2)
    invoiced_val = models.DecimalField(max_digits=19, decimal_places=4)
    created = models.DateTimeField(blank=True, null=True)
    createdby = models.CharField(max_length=100, blank=True, null=True)
    modified = models.DateTimeField(blank=True, null=True)
    modifiedby = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'txrcvd'
        unique_together = (('rcvid', 'productid', 'rinvoiceid', 'rinvoicedid', 'rcvidref'),)


class Txpayable(models.Model):
    paymentdid = models.AutoField(primary_key=True)
    paymentid = models.IntegerField(blank=True, null=True)
    rcvid = models.IntegerField(blank=True, null=True)
    bilyetguid = models.IntegerField()
    paymentid1 = models.CharField(max_length=64, blank=True, null=True)
    rcvid1 = models.CharField(max_length=64, blank=True, null=True)
    jenisbayar = models.CharField(max_length=510)
    kurstrx = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    totalbayar = models.DecimalField(max_digits=19, decimal_places=4)
    oriamount = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    tkonversibayar = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    tgljt = models.DateTimeField(blank=True, null=True)
    islunaslalu = models.SmallIntegerField(blank=True, null=True)
    currencyid = models.CharField(max_length=10, blank=True, null=True)
    kursbayar = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    kursharian = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    kursbayar2 = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    coa29 = models.IntegerField(blank=True, null=True)
    iscair = models.SmallIntegerField(blank=True, null=True)
    created = models.DateTimeField(blank=True, null=True)
    paytype = models.CharField(max_length=20, blank=True, null=True)
    createdby = models.CharField(max_length=30, blank=True, null=True)
    modified = models.DateTimeField(blank=True, null=True)
    modifiedby = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'txpayable'
        unique_together = (('jenisbayar', 'rcvid', 'paymentid'),)


class Txpaymenth(models.Model):
    paymentid = models.AutoField(primary_key=True)
    paymentno = models.CharField(max_length=100)
    paymentdate = models.DateField(blank=True, null=True)
    customerid = models.IntegerField()
    kursbayarh = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    totalpayment = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    totalpaymentf = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    isap = models.SmallIntegerField(blank=True, null=True)
    bunitid = models.IntegerField(blank=True, null=True)
    currencyid = models.CharField(max_length=20, blank=True, null=True)
    whsid = models.IntegerField(blank=True, null=True)
    coa31 = models.IntegerField(blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    pcpay1 = models.SmallIntegerField(blank=True, null=True)
    created = models.DateTimeField(blank=True, null=True)
    paynote = models.CharField(max_length=510, blank=True, null=True)
    createdby = models.CharField(max_length=30, blank=True, null=True)
    modified = models.DateTimeField(blank=True, null=True)
    modifiedby = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'txpaymenth'
        unique_together = (('paymentno', 'paymentdate', 'customerid'),)
